version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  producer1:
    build: ./producer
    container_name: producer1
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer:/usr/src/app
  
  producer2:
    build: ./producer
    container_name: producer2
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer:/usr/src/app

  producer3:
    build: ./producer
    container_name: producer3
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer:/usr/src/app

  
     
  consumer1:
    build: ./consumer
    container_name: consumer1
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer:/usr/src/app
  
  consumer2:
    build: ./consumer
    container_name: consumer2
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer:/usr/src/app
  
  consumer3:
    build: ./consumer
    container_name: consumer3
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer:/usr/src/app

  consumer4:
    build: ./consumer
    container_name: consumer4
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumer:/usr/src/app
    