version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
      image: redis:6.2.6
      ports:
        - "6379:6379"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes    
  
  producer_elefante:
    build: ./producer_elefante
    container_name: producer_elefante_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer_elefante:/usr/src/app
  
  producer_girafa:
    build: ./producer_girafa
    container_name: producer_girafa_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer_girafa:/usr/src/app

  producer_leon:
    build: ./producer_leon
    container_name: producer_leon_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer_leon:/usr/src/app
  
  producer_mono:
    build: ./producer_mono
    container_name: producer_mono_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer_mono:/usr/src/app

  producer_tigre:
    build: ./producer_tigre
    container_name: producer_tigre_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producer_tigre:/usr/src/app
  
  consumer_elefante:
    build: ./consumer_elefante
    container_name: consumer_elefante_kafka
    depends_on:
      - kafka
      - zookeeper
      - producer_elefante
    volumes:
      - ./consumer_elefante:/usr/src/app
  
  consumer_girafa:
    build: ./consumer_girafa
    container_name: consumer_girafa_kafka
    depends_on:
      - kafka
      - zookeeper
      - producer_girafa
    volumes:
      - ./consumer_girafa:/usr/src/app
  
  consumer_leon:
    build: ./consumer_leon
    container_name: consumer_leon_kafka
    depends_on:
      - kafka
      - zookeeper
      - producer_leon
    volumes:
      - ./consumer_leon:/usr/src/app

  consumer_mono:
    build: ./consumer_mono
    container_name: consumer_mono_kafka
    depends_on:
      - kafka
      - zookeeper
      - producer_mono
    volumes:
      - ./consumer_mono:/usr/src/app

  consumer_tigre:
    build: ./consumer_tigre
    container_name: consumer_tigre_kafka
    depends_on:
      - kafka
      - zookeeper
      - producer_tigre
    volumes:
      - ./consumer_tigre:/usr/src/app