version: '3'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  producer_elefante:
    build: ./producer_elefante
    container_name: producer_elefante_rabbit
    depends_on:
      - rabbitmq
    volumes:
      - ./producer_elefante:/usr/src/app

  producer_girafa:
    build: ./producer_girafa
    container_name: producer_girafa_rabbit
    depends_on:
      - rabbitmq
    volumes:
      - ./producer_girafa:/usr/src/app

  producer_leon:
    build: ./producer_leon
    container_name: producer_leon_rabbit
    depends_on:
      - rabbitmq
    volumes:
      - ./producer_leon:/usr/src/app

  producer_mono:
    build: ./producer_mono
    container_name: producer_mono_rabbit
    depends_on:
      - rabbitmq
    volumes:
      - ./producer_mono:/usr/src/app

  producer_tigre:
    build: ./producer_tigre
    container_name: producer_tigre_rabbit
    depends_on:
      - rabbitmq
    volumes:
      - ./producer_tigre:/usr/src/app

  consumer_elefante:
    build: ./consumer_elefante
    container_name: consumer_elefante_rabbit
    depends_on:
      - rabbitmq
      - producer_elefante
    volumes:
      - ./consumer_elefante:/usr/src/app

  consumer_girafa:
    build: ./consumer_girafa
    container_name: consumer_girafa_rabbit
    depends_on:
      - rabbitmq
      - producer_girafa
    volumes:
      - ./consumer_girafa:/usr/src/app

  consumer_leon:
    build: ./consumer_leon
    container_name: consumer_leon_rabbit
    depends_on:
      - rabbitmq
      - producer_leon
    volumes:
      - ./consumer_leon:/usr/src/app

  consumer_mono:
    build: ./consumer_mono
    container_name: consumer_mono_rabbit
    depends_on:
      - rabbitmq
      - producer_mono
    volumes:
      - ./consumer_mono:/usr/src/app

  consumer_tigre:
    build: ./consumer_tigre
    container_name: consumer_tigre_rabbit
    depends_on:
      - rabbitmq
      - producer_tigre
    volumes:
      - ./consumer_tigre:/usr/src/app