version: '3'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  producer1:
    build: ./producer
    container_name: producer1
    depends_on:
      - rabbitmq
    volumes:
      - ./producer:/usr/src/app

  producer2:
    build: ./producer
    container_name: producer2
    depends_on:
      - rabbitmq
    volumes:
      - ./producer:/usr/src/app

  producer3:
    build: ./producer
    container_name: producer3
    depends_on:
      - rabbitmq
    volumes:
      - ./producer:/usr/src/app

  consumer1:
    build: ./consumer
    container_name: consumer1
    depends_on:
      - rabbitmq
      - producer1
      - producer2
      - producer3
    volumes:
      - ./consumer:/usr/src/app

  consumer2:
    build: ./consumer
    container_name: consumer2
    depends_on:
      - rabbitmq
      - producer1
      - producer2
      - producer3
    volumes:
      - ./consumer:/usr/src/app

  consumer3:
    build: ./consumer
    container_name: consumer3
    depends_on:
      - rabbitmq
      - producer1
      - producer2
      - producer3
    volumes:
      - ./consumer:/usr/src/app

  consumer4:
    build: ./consumer
    container_name: consumer4
    depends_on:
      - rabbitmq
      - producer1
      - producer2
      - producer3
    volumes:
      - ./consumer:/usr/src/app
